- name: example_global_value
  path: $
  labels:
    environment: beta # static label

- name: example_value
  type: object
  path: $[*]?(@.severity == "info")
  labels:
    environment: beta   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp

- name: example_error
  type: object
  path: $[*]?(@.severity == "error")
  labels:
    environment: beta   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp
