- name: eventLog_global_value
  path: $
  labels:
    environment: edge_development # static label

- name: EventLog    #Prometheus adds _info
  type: object
  path: $[*]?(@.severity == "info")
  labels:
    environment: edge   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp

- name: EventLog_warning
  type: object
  path: $[*]?(@.severity == "warning")
  labels:
    environment: edge   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp

- name: EventLog_error
  type: object
  path: $[*]?(@.severity == "error")
  labels:
    environment: edge   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp

- name: EventLog_fatal
  type: object
  path: $[*]?(@.severity == "fatal")
  labels:
    environment: edge   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp