- name: eventLog_global_value
  path: $
  labels:
    environment: edge # static label

- name: eventLog_info
  type: object
  path: $[*]?(@.severity == "info")
  labels:
    environment: edge   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp

- name: eventLog_warning
  type: object
  path: $[*]?(@.severity == "warning")
  labels:
    environment: edge   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp

- name: eventLog_error
  type: object
  path: $[*]?(@.severity == "error")
  labels:
    environment: edge   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp

- name: eventLog_fatal
  type: object
  path: $[*]?(@.severity == "fatal")
  labels:
    environment: edge   # static label
    id: $.record_id      # dynamic label
    source_type: $.source_type # dynamic value
    event_code: $.event_code
    message: $.message
  values:
    info: 1             # static value
    timestamp: $.timestamp