#ARG ARCH="arm"
#ARG OS="linux"
#FROM quay.io/prometheus/busybox-${OS}-${ARCH}:glibc

FROM arm64v8/alpine:latest
LABEL maintainer="The Prometheus Authors <prometheus-developers@googlegroups.com>"
#COPY .build/${OS}-${ARCH}/json_exporter /bin/json_exporter

ARG ARCH="arm"
COPY ./json_exporter.${ARCH} /bin/json_exporter
COPY ./config.yml /bin/config.yml

EXPOSE      7979
USER        nobody
ENTRYPOINT  [ "/bin/json_exporter" ]
CMD ["http://127.0.0.1:8510/eventlog","/bin/config.yml"]