{
 "title": "Edge Node Monitoring",
 "description": "Edge Node Event Logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info,cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
   },
   { "name": "service", "query": "label_values(service)" },
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Event Log Metrics",
   "type": "graph",
   "description": "Info, Errors",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(EventLog_info{instance=\"$instance\",namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "Info"
    },
    {
     "expr": "count(EventLog_error_info{instance=\"$instance\",namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "Errors"
    },
    {
     "expr": "count(EventLog_warning_info{instance=\"$instance\",namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "EventLog_error_info{instance=\"$instance\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "EventLog_warning_info{instance=\"$instance\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Info Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "EventLog_info{instance=\"$instance\",namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  }
 ]
}