---
apiVersion: v1
kind: Service
metadata:
  name: edge-monitoring
  namespace: monitoring
  labels:
    k8s-app: edge-monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 7979
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edge-monitoring
  labels:
    k8s-app: edge-monitoring
spec:
  endpoints:
  - port: metrics
    interval: 30s
    scheme: http
  selector:
    matchLabels:
      k8s-app: edge-monitoring
  namespaceSelector:
    matchNames:
    - monitoring
---
apiVersion: v1
kind: Endpoints
metadata:
  name: edge-monitoring
  labels:
    k8s-app: edge-monitoring
subsets:
- addresses:
  - ip: 52.116.2.26
  - ip: 9.30.118.108
  - ip: 172.16.158.170
  ports:
  - name: metrics
    port: 7979
    protocol: TCP
